name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: generate snake.svg
        uses: damarsasiwilogo/snk@v2.0.0
        with:
          github_user_name: damarsasiwilogo
          outputs: dist/snake.svg

      - name: push snake.svg to the output branch
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: output
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}