name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: generate snake.svg
        uses: damarsasiwilogo/damarsasiwilogo/svg-only@v2
        with:
          github_user_name: damarsasiwilogo
          outputs: dist/snake.svg

      - name: push snake.svg to the output branch
        uses: damarsasiwilogo/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
